name     = "cljdevopshard"
location = "eastus"
network_address_space = "10.10.0.0/16"
aks_subnet_address_name = "snet-aks"
aks_subnet_address_prefix = "10.10.0.0/24"
subnet_address_name = "snet-appgw"
subnet_address_prefix = "10.10.1.0/24"
